import { useComplexLookupStore } from './stores/complexLookup';
import { useConfigStore } from './stores/config';
import { useInputsStore } from './stores/inputs';
import { useLoadingStateStore } from './stores/loadingState';
import { useManageProfileSettingsStore } from './stores/manageProfileSettings';
import { useMarcPreviewStore } from './stores/marcPreview';
import { useNavigationStore } from './stores/navigation';
import { useProfileStore } from './stores/profile';
import { useSearchStore } from './stores/search';
import { useStatusStore } from './stores/status';
import { useUIStore } from './stores/ui';
import { enhanceBoundStore } from './utils/selectors';

export const useStatusState = enhanceBoundStore(useStatusStore);
export const useLoadingState = enhanceBoundStore(useLoadingStateStore);
export const useMarcPreviewState = enhanceBoundStore(useMarcPreviewStore);
export const useProfileState = enhanceBoundStore(useProfileStore);
export const useInputsState = enhanceBoundStore(useInputsStore);
export const useConfigState = enhanceBoundStore(useConfigStore);
export const useUIState = enhanceBoundStore(useUIStore);
export const useSearchState = enhanceBoundStore(useSearchStore);
export const useComplexLookupState = enhanceBoundStore(useComplexLookupStore);
export const useNavigationState = enhanceBoundStore(useNavigationStore);
export const useManageProfileSettingsState = enhanceBoundStore(useManageProfileSettingsStore);
